version: '3.8'

services:
  nginx:
    image: nginx:1.23-alpine
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - app-data:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  php:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - app-data:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
